- hosts: all
  connection: local
  become: yes
  gather_facts: True

  tasks:
  - name: include vars
    include_vars: /vagrant/ansible-playbook/versions.yml
    
  #- debug: var= k8s_minor_ver


  ## Docker CE のインストール
  #
  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - nfs-common
      - docker-ce{{ docker_version }}
      - containerd.io

  - name: usermod -aG docker vagrant
    user:
      name: vagrant
      groups: docker

  ## カーネル設定変更
  #
  - name: Set sysctl 
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: "1"
      sysctl_set: yes
      sysctl_file: /etc/sysctl.conf      
      state: present
      reload: yes

  ## GlusterFS のインストール
  #
  - name: Add GlusterFS Repository
    apt_repository:
      repo: ppa:gluster/glusterfs-7

  - name: Install GlusterFS client
    apt:
      name: glusterfs-client
      state: present
      update_cache: yes


  ## Kubernetes のインストール
  #
  - name: swapoff
    command: swapoff -a
    register: swap

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  - name: Install kubectl
    apt:
      name: kubectl{{ k8s_version }}
      state: present
      update_cache: yes

  - name: Install kubelet
    apt:
      name: kubelet{{ k8s_version }}
      state: present
      update_cache: yes

  - name: Install kubeadm
    apt:
      name: kubeadm{{ k8s_version }}
      state: present
      update_cache: yes
  ## ifconfigを使えるように、net-toolsをインストール
  #
  - name: Install net-tools
    apt:
      name: net-tools
      state: present
      update_cache: yes

  ## k8sのVagrant対応に、ノードのIPアドレスを設定 
  #
  - name: include vars
    include_vars: /vagrant/ansible-playbook/versions.yml


  ## HostOnly Interface の IPアドレス取得
  #
  - name: getting hostonly ip address
    command: ifconfig enp0s8
    register: ip
  - debug: var=ip.stdout_lines[1].split('inet')[1].split(' ')[1]



  ## 10-kubeadmin.conf に --node-ipを追加
  #
  - name: change 10-kubeadm.conf for v1.11 or later
    replace:
      dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      regexp: 'KUBELET_EXTRA_ARGS$'
      replace: KUBELET_EXTRA_ARGS --node-ip={{ ip.stdout_lines[1].split('inet')[1].split(' ')[1] }} --cluster-dns=10.32.0.10

    when: k8s_minor_ver |int > 11

  - name: change 10-kubeadm.conf for v1.9 or v1.10
    replace:
      dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      regexp: '^Environment="KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local"$'
      replace: Environment="KUBELET_DNS_ARGS=--cluster-dns=10.32.0.10 --cluster-domain=cluster.local --node-ip={{ ip.stdout_lines[1].split('inet')[1].split(' ')[1] }}"
    when: (k8s_minor_ver == "10") or (k8s_minor_ver == "9")


  ## 変更を反映
  #
  - name: daemon-reload and restart kubelet
    systemd:
      state: restarted
      daemon_reload: yes
      name: kubelet

